### ISSUE TITLE
[installation] next step after FreeACS installation

### ISSUE THREAD

**Issue by jcmosquera2001** [freeacs/freeacs#116]
Hi,

I was able to install FreeACS with all components on Centos 7.5 + MySQL 8 (it is a Linode VM).
So far so good! :)

We have an small installation with 20- ONTs ZTE-F660 that I want to start configuring using TR069. 

Do I have to define any king of Unit Type at GUI ? 
Which is the default user/pass to configure on the devices ?

Regards,
Jose

**Comment by pingwiniasty** [comment]
Jarlah is right. Set TR069 in discovery mode
`discovery.mode = true`
 then new units will be available in web panel.

In discovery mode you not need user and pass for devices. Devices pass it at first request

**Comment by jarlah** [comment]
There has been made a great deal of improvements to the install process. We now have deb and rpm packages. And docker images.

I suggest download the rpms from the latest release and install them in centos. But disable the old services with systemctl disable freeacs-[module]. And you might need to Port some custom config to /etx/default/freeacs-[module]

**Comment by jarlah** [comment]
Aaaaand now I have added install script for CentOS. See wiki.
