### ISSUE TITLE
[web] UnitType with hardware version

### ISSUE THREAD

**Issue by pingwiniasty** [freeacs/freeacs#12]
Hi!
I glad to see that project is active now :)

We have freeacs running for about 20k units, with 5 different types.
In our case we added to UnityType hardware version. Because some vendors (like ZTE on GPON F660) makes a lot of changes beetween hardware revision in one device model and in TR069 tree. With that change we are able to make different profiles to it. Look at screenshoot

![image](https://user-images.githubusercontent.com/14076845/39857112-75f46d76-5432-11e8-8a93-1efaaa2722a4.png)

There is a patch for that. It works for us. (for old repository)
[hw_version_in_unity_type_patch.txt](https://github.com/freeacs/freeacs/files/1990673/hw_version_in_unity_type_patch.txt)

If you want I can add PR for that, but now no have configured workspace for java.

**Comment by jarlah** [comment]
Nice to see that someone "checks in". I need to know if people are using freeacs and obviously you do :)

I am working on a lot of things atm, but the web project is very much alive and kicking in a local development environment. The project is now using maven with embedded jetty (for local testing) so if you download community edition of intellij and open the project in intellij, everything should just work :)

Heres how standard web looks now. 

![screenshot_2018-05-10_10-02-59](https://user-images.githubusercontent.com/404102/39859295-b2924aee-5439-11e8-9b31-98d31b89b5b6.png)

**Comment by jarlah** [comment]
Note, you might need to add a run configuration to run clean install with embedded maven in intellij if you dont have maven installed in terminal

**Comment by jarlah** [comment]
@pingwiniasty I have converted the web module to spring boot (in this PR) ... its sooo much better now .. and hopefully i havent introduced any bugs ... I think I have actually closed a security hole ...

**Comment by jarlah** [comment]
I see a lot of cosmetic changes in your version of web. And i am not sure what this issue is really about, so lets clearify that before we go further with this issue :)

**Comment by pingwiniasty** [comment]
Cosmetics is not important right now.

We are added `InternetGatewayDevice.DeviceInfo.HardwareVersion` to UnitType string, because some vendors makes chuge changes in TR069 tree between Hardware revisions. With that changes we can simple manage groups and profiles without making any scripts to do it. In my opinion this is not cosmetic, but important functionality to simplify things

**Comment by pingwiniasty** [comment]
I leave some questions in Gitter, could You check it?

**Comment by nortdata** [comment]
Sorry to revive an old thread. Im new here, i register right now just to contact pingwiniasty. I saw you was talking about f660. Could you please provide me with parameters for this ont router? Im working with this, and im testing freeacs. Right now i just get a couple of simple parameters. I need to be able to set samba, telnet and all the config from these routers. Thanks you and sorry my english.
