### ISSUE TITLE
Checking public IP in Kick class must be configurable

### ISSUE THREAD

**Issue by pingwiniasty** [freeacs/freeacs#13]
This line is checking if the connection URL is on public IP. But in modern networks, communication with device to configure it, is on dedicated VLAN with private IP. Maybe You can add option in configuration to disable checking Public IP or remove this totally from code?

https://github.com/freeacs/freeacs/blob/efc4a61149fcbbe4b77f1d3cb6367e3b19954c14/stun/src/main/java/com/owera/xaps/stun/Kick.java#L75

 In our modification I removed logic from method isPublic from 
`common com/owera/common/util/IPAddress.class`

**Comment by jarlah** [comment]
I will take a look at it :) Its on the top on my list, but its also a low hanging fruit that you could potentially open a pull request for yourself. See my other comment about intellij in the other issue you made.

**Comment by jarlah** [comment]
I will make a release candidate soon, that contains this fix.
