### ISSUE TITLE
Ignore vendor config file request

### ISSUE THREAD

**Issue by jogermech** [freeacs/freeacs#137]
Hi, I noticed, that ACS requests for vendorconfigfile node in couple with some other parameters, but my device doesn't support this node, so it returns fault for the whole GPV request.
I found it can be disabled by "quirks.Unit Type Name=ignorevendorconfigfile" option in TR069 properties file. So, I added it to freeacs-tr069 file in /etc/default but it looks like ACS doesn't recognize it
Any suggestions? 
I care that my unit type contains "space" symbol, but as far as I understand from docs it must match DeviceInfo.ModelName parameter. It that true

**Comment by jarlah** [comment]
You have hit an interesting problem. I had to rewrite the quirks syntax because  space in property key is not valid. Give me some time and i will sort it out for you. I am still working on docs And this needs updated docs ;)

**Comment by jogermech** [comment]
Hi, Jarl. Thank you for supporting my requestst.
Speaking of docs. Could you compile some guide on building project from the source code (at least could you plan to do it in some future)? I see some major limitations for my needs in current freeacs implementation, I would try to adapt it, but I need some guideline to start dive into the deep

**Comment by jarlah** [comment]
1. Install jdk8
2. Install sbt. Check sbt website for instructions
3. cd /freeacs/checked/out
3. sbt debian:packageBin

**Comment by jarlah** [comment]
If you find any improvements that work for you feel free to open a pull request.

**Comment by jarlah** [comment]
You can download community edition of idea and install Scala plugin and then open the project in There

**Comment by jarlah** [comment]
But it is Java. Just using Scala build tool

**Comment by jogermech** [comment]
So, what will be an output? *deb?

**Comment by jarlah** [comment]
Yep. For rpm it's a tiny bit more os coupled. On Ubuntu install rpm package with apt instsll rpm and then sbt rpm:packageBin. For docker it's another story. Tell me if you are using docker.

**Comment by jogermech** [comment]
No, not using, but if it makes workflow more simple and it's free then I can try it

**Comment by jarlah** [comment]
You just install docker and run sbt docker:publishLocal and then change into the scripts folder in command line and run docker-compose -p freeacs up -d

**Comment by jarlah** [comment]
On Windows you get docker compose for free. On Linux it's separate install

**Comment by jogermech** [comment]
It seems still uses default settings
Maybe I'm doing something wrong. Nevertheless I can see parameters on device, probably received from GPV IGD. request (which seems is running despite of parameters configured in unit type)
[tr069.log](https://github.com/freeacs/freeacs/files/2118178/tr069.log)
[tr069-conversation.log](https://github.com/freeacs/freeacs/files/2118179/tr069-conversation.log)

**Comment by jogermech** [comment]
TR069 server settings in /etc/default are:
```

auth_method=digest
....
QUIRKS=Smart\u0020Box=ignorevendorconfigfile
```

**Comment by jogermech** [comment]
@jarlah Unfortunately I'm in a business trip for next two weeks and have no remote access for my test environment.

**Comment by jarlah** [comment]
no problem @jogermech

**Comment by jogermech** [comment]
Hi, Jarl. Just checked. It works in 12.9
I was just a little bit confused with two config files: one in /etc/default and another in /opt/freeacs...
But yeah, now it doesn't request for the whole tree (which was caused by Vendor Config File parameter missing.
so, I believe issue can be closed

**Comment by jarlah** [comment]
Closing this. But Yes. It' might be confusing with two files. But in the end the files in /etc/default should just be ignored. :)
