### ISSUE TITLE
Nginx is difficult/useless in docker 

### ISSUE THREAD

**Issue by jarlah** [freeacs/freeacs#157]
For tr069 remote host and real ip is not correct. Unit doesnt get correct public ip. Solution is to forward service ports to host and connect directly. This problem only applies to docker deployments. Can also be solved by setting docker compose to host network mode

**Comment by jarlah** [comment]
forget it

**Comment by Cougar** [comment]
Should be doable using `proxy_set_header X-Real-IP $remote_addr;` or similar in Nginx config. I guess that in most deployments some sort of proxy/firewall should run between clients and server anyway. Also TLS(SSL) is much easier to implement this way today.
