### ISSUE TITLE
Could not compile source code due to the error "unmappable character for encoding UTF-8"

### ISSUE THREAD

**Issue by sabbane** [freeacs/freeacs#169]
By trying to compile the source code many character mapping errors are displayed and the build fails. Here is one of these errors:
`freeacs\webservice\target\src_managed\main\com\github\freeacs\ws\xml\AddOrChangeProfileRequest.java:4:1:` unmappable character for encoding UTF-8`

After changing the coding within "build.sbt" from "UTF-8" to "ISO-8859-1" the build process is successful. So, I think the character encoding should be changed to "ISO-8859-1".

**Comment by jarlah** [comment]
Havent tested on Windows so it's just a shot in the dark.

**Comment by jarlah** [comment]
i suggest using Intellij and to configure UTF-8 file encoding in Intellij settings
![encoding](https://user-images.githubusercontent.com/404102/43950382-71cce5b0-9c90-11e8-953e-7cdf69b03a6e.png)
Try dat.

**Comment by sabbane** [comment]
Indeed it was a system configuration. I'm compiling within windows powershell (I'll try with eclipse later) and now the build is successful after setting the following system environement variable:
`JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8`

**Comment by jarlah** [comment]
Great :) Closing ;)
