### ISSUE TITLE
./install.sh: line 101: install.sql: No such file or directory

### ISSUE THREAD

**Issue by wilsonfl** [freeacs/freeacs#171]
Where can I find the "install.sql"?
TKS.

**Comment by jarlah** [comment]
ubuntu or centos? I just tried to run the script command found in the wiki on a fresh ubuntu in virtualbox. No such error message.

**Comment by jarlah** [comment]
https://github.com/freeacs/freeacs/wiki/Get-started#install-script

**Comment by wilsonfl** [comment]
The error occurred in Ubuntu 14.04(64-bit), not freash.
In Ubuntu 16.04(32-bit), fresh, it's no any error message.
Thanks for your reply.

**Comment by jarlah** [comment]
1404 is not supported. To use script Ubuntu must be 16.04 or above. Closing
