### ISSUE TITLE
Firmware file upload fails

### ISSUE THREAD

**Issue by jogermech** [freeacs/freeacs#172]
Tried to upload firmware file via Files and Scripts -> Files menu and got nginx error after press "Upload file" button:
"413 Request Entity Too Large"

**Comment by jogermech** [comment]
2.0.1 fresh install by install.sh

**Comment by jogermech** [comment]
FW file size is about 16M

**Comment by jarlah** [comment]
Ok. Thats solvable. If it's install script based we can hot patch your nginx config while you wait for me to patch the service. If it's docker i can also fix that. See https://www.google.no/amp/s/www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/amp/ for hotfix.

**Comment by jarlah** [comment]
Closing this as there is bigger fishes to fry atm. You can follow guide above to adjust nginx to allow bigger upload payloads
