### ISSUE TITLE
change acs username

### ISSUE THREAD

**Issue by mathieuxilan** [freeacs/freeacs#176]
Hi,

I successfully installed freeacs on a debian server to manage lte cpe. All CPEs come with the same username/password by default (tr069). So I followed the FAQ: "All my devices have the same ACS-user/pass - can this be fixed?"
Unfortunately, the script execution always fails, with the message "The context switch to ut:ODU/ was not possible".
The model name has a "/" in its name, so has the unit type, "ODU/xxx/yyy", could it be the problem? the argument looks then like that: "-uut:ODU/MT422e/MT422e/pr:Default/un:tr069"

thanks

**Comment by mathieuxilan** [comment]
Hi,

This seems to cause a problem when I try to make my cpe download a firmware, because of the "/" in the requested URL probably. 
My unit type has been created with the auto discovery feature, how come there is a "/" in it ? 

thanks

**Comment by jarlah** [comment]
@mathieuxilan i have added a parsing logic where the product class is received. For your case replacing forward slash with a dash. But in the future maybe i will add a non word character filter. But i need to test out simple steps first and maybe this enough. In your case your ODU/xxx/yyyy would be parsed as ODU-xxx-yyyy

**Comment by jarlah** [comment]
This is solved and should be fixed in 2.0.3. Closing. Please open new issue if still a problem
