### ISSUE TITLE
[shell] Calling external scripts (like bash or anything)

### ISSUE THREAD

**Issue by pingwiniasty** [freeacs/freeacs#21]
What do you thing about calling external (system) scripts from Fusion shell?
Good option it when we can add line to script, to run this program with parameters.
In the past, we have some troubles with one type of device. Manufacturer was send to us some program to repair it. In other case we can write more complex scripts in other lang. to do something, what we need.

What do you thing about it?

**Comment by jarlah** [comment]
I am currently in the process of getting the application deployment ready. Still a couple of things left to do. But when I have a working deployment system, I can start look at things like this.
I am little bit sceptical. Its very difficult to make this kind of thing portable across operating systems. But I can try to see if there is a way to calling applications in the guest os in java. Not sure, dont do that alot. Again, a little bit sceptical. But hey, its a challenge. But not challenge accepted just yet ;)
