### ISSUE TITLE
data model evolution: Refresh Unit-Type Parameters

### ISSUE THREAD

**Issue by lindererik** [freeacs/freeacs#219]
Hello,

I would need to add Parameters to an already existing Unit-Type as there are new parameters for new SW version

Can I trigger re-discovery in some way ? Or do I have to delete the unit-type to rediscover ? (What would happen to exisiting units ?)

Thanks for any tip (I'm ready to hack the database in last resort  )

Cheers
erik

**Comment by jarlah** [comment]
```
/**
   * The discovery flag, set to run GetParameterNames on device - update the unittype configuration.
   */
  public static final String DISCOVER = "System.X_FREEACS-COM.Discover" ;
```
Set it to 1.:)

**Comment by jarlah** [comment]
At least thats the theory. I have no unit test for this scenario. Crossing fingers

**Comment by jarlah** [comment]
No response in almost a month. Closing
