### ISSUE TITLE
[web?] Application level password failure

### ISSUE THREAD

**Issue by samgior10** [freeacs/freeacs#265]
My credentials where created as a user, but I can't use them with the web GUI.
How can I access the web GUI and reset the password? FreeACS

**Comment by jarlah** [comment]
Docker?

**Comment by jarlah** [comment]
Tested on Ubuntu. Seems to work. In master and possibly docker there is now a little revolution going on in regards to default user and password. Thats why i Wonder if you are on bleeding edge or stable v2.1.0

**Comment by jarlah** [comment]
i have now updated docker hub images. Please help me out on what platform you are using?

**Comment by samgior10** [comment]
Hi Sorry for the delay response, ACS was loaded on the server and when I try and access the ACS web browser the password user created on the server is not recognised. "Bad Credentials"  I tried using admin/freeacs and a combination of uppercase and indicated in some blogs with no success.

**Comment by jarlah** [comment]
ok. check in web.log. its in /opt/freeacs-web/logs/web.log

There is an auto generated password there. 

This feature is on its way out of the ocde. And the old behaviour is on its way back. with admin/freeacs.

New release coming today or tomorrow that removes the auto generated password in log feature.

Sorry for the troubles.

**Comment by jarlah** [comment]
New release available. You can download and install the freeacs-web deb file manually with dpkg -i freeacs-web*.deb to get up and running again. To see more:

https://www.tapatalk.com/groups/freeacsforum/v2-1-2-t14.html#p66

**Comment by samgior10** [comment]
Thanks for your prompt response, we haven't tested it yet.
I'll update you on the results.
