### ISSUE TITLE
Error in the install.sh

### ISSUE THREAD

**Issue by thiagosape** [freeacs/freeacs#279]
Hello everyone !
I have installed a minimal and clear instance of Ubuntu Server 16.04 following the Fusion.Installation.pdf.

I have the following output:

```
All necessary FreeACS resources are available.

install.sh: 117: install.sh: [[: not found

Specify/create the password for the FreeACS MySQL user.
NB! The FreeACS MySQL user name defaults to 'acs'
NB! If the user has been created before: Do not try to change the password - this script will no handle the change of password into MySQL, but the configuration files will be changed - causing a password mismatch!!
Using mysql root pw:
Enter the password: 
```

I put the ubuntu user password, ubuntu root password and the mysql root password defined during the installation steps
None worked.

After try passwords 6 times it is show that output:
```
The FreeACS MySQL database users 'acs' and 'acs'@'localhost' is not found in the mysql.user table. Maybe you stated the wrong MySQL root password??
Please make sure this is corrected, either by running the equivalent of the following SQL-statements:

Running as MySQL Root user:
CREATE DATABASE acs
GRANT ALL ON acs.* TO 'acs' IDENTIFIED BY 'A_PASSWORD'
GRANT ALL ON acs.* TO 'acs'@'localhost' IDENTIFIED BY 'A_PASSWORD'

Below are stderr output from the commands above - they may indicate the problem at hand:

ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
root@acs:/home/acs#
```
Why does this happening ? I suppose that error at line 117 has something related.

Many thanks

**Comment by jarlah** [comment]
Thanks for the report. I will look into it, sometime, if not done by someone else.

**Comment by thiagosape** [comment]
I would like to contribute, is there something simple to do initially?

**Comment by pingwiniasty** [comment]
Hi, I reproduced it using /bin/sh instead of /bin/bash
@thiagosape are you launched scirpt typing `$ sh install.sh`?

Script uses bash syntax which can be different of sh

**Comment by thiagosape** [comment]
> 
> 
> Hi, I reproduced it using /bin/sh instead of /bin/bash
> @thiagosape are you launched script typing `$ sh install.sh`?
> 
> Script uses bash syntax which can be different of sh

Yes I have used `# sh install.sh`

Now I used `# bash install.sh` and everything went well. Thank you!!
I didn't paid attention on that.
Thanks !!!
