### ISSUE TITLE
[all] java.lang.OutOfMemoryError: Metaspace   ---->WebService

### ISSUE THREAD

**Issue by penaivanalejandro** [freeacs/freeacs#287]
Hello @jarlah , I'm doing tests with the webservice and today I wake up with this error:
![error_webservice](https://user-images.githubusercontent.com/29745524/52489684-7b8e9800-2b88-11e9-9c0f-270093e1bedd.png)

Do you know if there is a fix to increase the metaspace for this module?

**Comment by jarlah** [comment]
i suppose you have some ram available. Just increase metaspacesize to 100 or 200 or something, like ```-XX:MaxMetaspaceSize=200m````. and if you have the memory, set ```-Xmx=1024m```. It has been running for 2 weeks i see, not good, but the memory parameters are adjustable for your liking. Its in application.ini under /opt for the module

**Comment by jarlah** [comment]
fix it, let it run for another to or three weeks untouched, and we can take it from there. But i will take a deeper look at this problem, by adding best practice jvm params for memory management.

**Comment by penaivanalejandro** [comment]
Thanks @jarlah 
Ready, I'm going to try these 3 weeks ...
Excellent support, thank you very much.

![webservice memory](https://user-images.githubusercontent.com/29745524/52496810-07f58680-2b9a-11e9-8d7e-78089c1ec008.png)

**Comment by jarlah** [comment]
Ill leave this issue open since i need to fix the default config in webservice module and possibly others.

Or anyone else can do it. Really.

**Comment by pingwiniasty** [comment]
1GB of memory and ~256M to MetaSpace?

**Comment by pingwiniasty** [comment]
@penaivanalejandro Can you tell me, are you have some troubles with webservice? I ran it with ~20 CPEs ang 2GB of memory. After some time, webservice java process uses 100% of CPU

**Comment by pingwiniasty** [comment]
It seems it is a problem with trying to fetch CPE which not exist in ACS.

**Comment by penaivanalejandro** [comment]
Hi @pingwiniasty I have 8Gb of memory....  this is the status on the machine...

I have this CPE today:
![Equipos](https://user-images.githubusercontent.com/29745524/54618390-91fdfe00-4a28-11e9-9ca8-8d413f548d8c.png)

systemctl status to webservice:
![systemctl](https://user-images.githubusercontent.com/29745524/54618433-a215dd80-4a28-11e9-8816-e9d1beb1dec3.png)


Hardware:
![Hardware](https://user-images.githubusercontent.com/29745524/54618474-b4901700-4a28-11e9-9d8d-b049923f5cd0.png)


![top](https://user-images.githubusercontent.com/29745524/54618485-b8bc3480-4a28-11e9-8797-c4e550fdff90.png)


And I do a test to get a Unit:

![test_webservice](https://user-images.githubusercontent.com/29745524/54618603-e903d300-4a28-11e9-971e-8e0ddb4768ba.png)

![test2](https://user-images.githubusercontent.com/29745524/54618611-ec975a00-4a28-11e9-884d-af58f5174d66.png)

**Comment by jarlah** [comment]
Might not be related. But. 

I have a hunch. The dbi way of doing things is very impractical. Each user must have its own DBI instance which leads to many long living DBI instances.

We need to figure out how to do multi user on singleton dbi.

**Comment by jarlah** [comment]
This multi user singleton pattern should also be considered for new web implementation.
