### ISSUE TITLE
Unit Jobs page - error 500

### ISSUE THREAD

**Issue by pingwiniasty** [freeacs/freeacs#298]
When I trying to visit Unit-Jobs, server responses with 500 error.
I checked it and there is an error with default contructor in UnitJobPage, this class has 2 contructors.

getWebPage method in Main.java returns wrong contructor. It logic is broken, because always check first constructor.
https://github.com/freeacs/freeacs/blob/b778d8129a7ddaddcd198a861629c033a3c49f40/web/src/main/java/com/github/freeacs/web/app/Main.java#L59-L66

**Comment by jarlah** [comment]
I have a fix. Refactor blunder.

**Comment by pingwiniasty** [comment]
you are so fast :D

**Comment by jarlah** [comment]
:D

I dont like the passing around datasource thing. But this is remnants of old code where i used spring controllers that auto wired datasource in constructor. If you want to help you can check if there is other similar constructors with equal uselessness :)

**Comment by jarlah** [comment]
You can Just checkout branch and continue on it directly. You should be able to contribute on it

**Comment by jarlah** [comment]
Merged pull request #299

**Comment by pingwiniasty** [comment]
I checked other pages and I not found other constructors

**Comment by jarlah** [comment]
done
