### ISSUE TITLE
reboot CPE

### ISSUE THREAD

**Issue by CuteTT** [freeacs/freeacs#309]
I want to reboot CPE by freeacs server 
I add this job 
![image](https://user-images.githubusercontent.com/38638768/55778539-bdc74d80-5ad5-11e9-9d72-cbc668d00245.png)
but It was not reboot immediately until CPE INFORM.
How to control CPE reboot immediately use by tr069_script.

**Comment by jarlah** [comment]
I think you would need to perform a kick. I dont remember how or if its possible in script. I will maybe check it out. But my gut feeling is that rebooting a fleet of cpes is not possible without configuring advanced properties to be able to reach those cpes via tcp or udp, in a profile or in each unit.

**Comment by zzzacbbt** [comment]
Hi .jarlah.I don't know how to perform a kick.Could you tell me?

**Comment by pingwiniasty** [comment]
@zzzacbbt I will check it tomorrow.

**Comment by zzzacbbt** [comment]
OK,thank you @pingwiniasty

**Comment by pingwiniasty** [comment]
@zzzacbbt Please attach here tr069-conversation.log and service windows configuratio. You can check it in Unit profile -> Select Action -> Service Window.

**Comment by zzzacbbt** [comment]
![image](https://user-images.githubusercontent.com/38638768/56021212-72ae7400-5d3b-11e9-902f-e0b2bfd4eb4b.png)

**Comment by zzzacbbt** [comment]
How to get tr069-conversation.log

**Comment by techdpnn** [comment]
default.
`/opt/freeacs-tr069/logs`

**Comment by zzzacbbt** [comment]
[tr069-conversation.log](https://github.com/freeacs/freeacs/files/3072285/tr069-conversation.log)

**Comment by zzzacbbt** [comment]
[devicestatus.zip](https://github.com/freeacs/freeacs/files/3072324/devicestatus.zip)
After CPE INFROM,It did the script and reboot,and always do something like this.
should I re-install the server?

**Comment by techdpnn** [comment]
i want to discuss with you  about freeacs ,could you please leave a email or something else  to contact with you .thanks

**Comment by techdpnn** [comment]
@zzzacbbt  i want to ask you some question about freeacs ,could you please leave a email or something else  to contact with you .thanks

**Comment by zzzacbbt** [comment]
13122231591@163.com

**Comment by dariosky75** [comment]
@zzzacbbt
Hi, are you able to kick a single device from the web console? I think you should be first getting this done before trying the other

**Comment by zzzacbbt** [comment]
I don't understand how to kick a device,Do you mean delete the unit?

**Comment by dariosky75** [comment]
@zzzacbbt 
I am a newbie on the subject so bear with me. 
KICK basically means that your are pinging the CPE to tell "get back in touch with the ACS and provision" otherwise you will have to wait periodic inform Interval set on the CPE.
For KICK to work  parameters should be properlu configured(authentication).
If you go to a specific unit configuration something like   
XXXXXXX/web/index?page=unit-configuration&init_refreshpage=Refresh
You see the provisioning sections all of the 4 commands in there perform a KICK to begin with
Provision, ReadAll, Reboot, Reset


![Cattura](https://user-images.githubusercontent.com/10060556/57063589-0aacd700-6cc4-11e9-8bfc-fb406f5c1d7c.PNG)

**Comment by jarlah** [comment]
To get this working satisfactory, you should set connectionrequest[url|username|password] unittype parameters to RA. Some cpes doesnt reply with other than blank on these. If the cpe doesnt send the values of these parameters, i often feel its very difficult to get around the problem and i am working to find a solution for this. In the mean time its possible to set a series of system parameters to enable the acs to build up a dynamic kick url. But its a bit flaky at the moment.
