### ISSUE TITLE
Cannot get FreeACS to see my CPEs

### ISSUE THREAD

**Issue by knackrack615** [freeacs/freeacs#313]
Hello, after many attempts and trying anything i could think of i still can't get my CPEs to show in FreeACS

I've set discovery.mode to true and also set authentication to none

I'm running FreeACS in docker and i've applied the settings both by editing the .env file (which didn't seem to do anything) and by manually editing the application.conf inside the docker container.

The only thing i'm getting in the logs is this: https://hastebin.com/pasirijige.coffeescript (nothing in tr069 related logs)

EDIT
--------

So it turns out that for whatever reason i need to use my IP instead of a Domain name for my CPEs to be able to properly communicate with FreeACS, i've managed to get them to show up now, however it looks like they're not sending their data properly (Log: https://hastebin.com/zalumazaha.rb)

**Comment by jarlah** [comment]
Server does not recognize GetRPCMethods.

**Comment by knackrack615** [comment]
Alright, thanks for clarifying!

**Comment by jarlah** [comment]
@knackrack615 i have now implemented support for both receiving and sending GetRPCMethods. But there is currently no logic to trigger this method to the device in the server. But it will properly receive the request and decide to return a list of methods supported.

**Comment by jarlah** [comment]
Not released yet.
