### ISSUE TITLE
How to reboot device?

### ISSUE THREAD

**Issue by freedomwarrior** [freeacs/freeacs#341]
Hello. 
I enabled tr069 discovery mode, and I see my test router.
Simple stuff, how can I reboot this router from freeacs panel?

**Comment by yrong** [comment]
unit configuration->reboot
http://localhost:8081/web/index?page=unit-configuration&init_refreshpage=Refresh

**Comment by freedomwarrior** [comment]
I try, but there is no effect. Did I need to configure something more than auto_discover?
![Screenshot from 2019-07-29 15-14-21](https://user-images.githubusercontent.com/6192135/62047804-fa998a80-b213-11e9-82db-03095bc17a87.png)

**Comment by yrong** [comment]
you need to start stun server and be sure that cpe support tr111

**Comment by freedomwarrior** [comment]
My device supports only tr069. So without tr111 supports, I can`t do some basics stuff like reboot/support etc?

**Comment by yrong** [comment]
then you will wait until cpe sending 2 periodical inform to  do such things

**Comment by yrong** [comment]
Btw, the current freeacs does not support send tcp connection request to cpe directly. In my forked version I've add some logic for that and feel free to test.
https://github.com/freeacs/freeacs/pull/342/commits/a8458c2b319c7680afd39998481a659f60edac7a

**Comment by freedomwarrior** [comment]
Ok, thanx a lot.
