### ISSUE TITLE
tr069 testing framework commands are not recognized

### ISSUE THREAD

**Issue by kumara-chn** [freeacs/freeacs#344]
tr069 testing framework commands are not recognized. Any help to resolve this?

/ut:xxxxxxxx/>generatetc
2019-08-09 02:37:32 ERROR com.github.freeacs.shell.Processor - Output: /ut:BGW210-700/>The command generatetc was not recognized.
Error: The command generatetc was not recognized.

**Comment by jarlah** [comment]
The testing system has been totally removed due to its tentacles reaching deep into the code and making it so much more complicated. Obviously not removed from Shell. I will think about it.
