### ISSUE TITLE
getUnitIds returns only 50 unit ids

### ISSUE THREAD

**Issue by mstrasser2** [freeacs/freeacs#347]
Hello,

i need to read all unit ids from the acs server but the function 'getUnitIds', which is responsible to do so, only returns 50 ids.
I used the unittype or profile as filter option.
However i do not understand why i only get 50 unit ids back.
Maybe someone can help me to solve my issue.

Thanks

**Comment by jarlah** [comment]
This should be an easy problem to solve or figure out. But give me some time.
