### ISSUE TITLE
installation is too complicated on ubuntu

### ISSUE THREAD

**Issue by qianguozheng** [freeacs/freeacs#349]
Hi, is it possible to make it easy to install on Ubuntu system ?

**Comment by jarlah** [comment]
Nice. Are you using the prerelease? Thats the only version that is hard to install. I dont see how the current stable version is hard? Errors ? Or too many prompts?

**Comment by baronkis** [comment]
Hi, I install freeacs on ubuntu 16.04 and it`s easy install script. You can try command 
wget https://raw.githubusercontent.com/freeacs/freeacs/master/scripts/install.sh -v -O install.sh && chmod +x install.sh && sudo ./install.sh
