### ISSUE TITLE
Seeking maintainer(s)!

### ISSUE THREAD

**Issue by jarlah** [freeacs/freeacs#351]
I have thought about whether i have enough time and energy to continue the project. 

Sorry to say i concluded that i havent. 

Seeking one or more developers that can continue this project. As long as the License is kept as is.

**Comment by jarlah** [comment]
Maintainers have been found. Lead maintainer is now @pingwiniasty. I will still be in the background helping maintainers do what they need to do. But i will not enforce any decisions.

**Comment by pingwiniasty** [comment]
Hi! Thanks @jarlah for entry post :D 

Currently with @indiwidu we want to recreate whole web package. There will be full REST API on the backend and Vuejs SPA on the frontend. 
This could contain breaking changes with current version, but we want to make work with freeacs easiest.

Give us time so we can prepare a list of changes and things to do with new version.

**Comment by yrong** [comment]
is this project still alive?  I can provide help if needed

**Comment by jarlah** [comment]
@yrong I usually never check this project anymore, so you were lucky now ;) . in theory @pingwiniasty took the challenge. However, all of us have a day job. If you or @pingwiniasty, or anyone else, can make fixes and open pull requests however, its not too time consuming for me the briefly code review it and merge it and possibly make a release from time to time.
