### ISSUE TITLE
Moving Units within Groups using Shell Script

### ISSUE THREAD

**Issue by tolukosimi** [freeacs/freeacs#355]
Hello,

I am looking at a simple case of being able to move units between groups (in the case that a job is applied to a group and after the application, i want the unit to be moved to another group).

Is there anyway to achieve this?

Regards

**Comment by pingwiniasty** [comment]
Look at docs (page 25) https://github.com/freeacs/freeacs/blob/master/web/docs/Fusion%20Web%20User%20Manual.pdf

You can create parameter in unit type, then you be able to set value of parameter, which you created, by running script in job

`setparam System.X_FREEACS.GroupName VALUE`
