### ISSUE TITLE
[all] Suggest a better way to monitor services, now that they are all bundled with actuator

### ISSUE THREAD

**Issue by jarlah** [freeacs/freeacs#66]
I am going to remove monitor. I need to suggest a better way  monitor modules. Maybe inter module (cluster?) monitoring? Need to think about this. One thing for sure, I cannot maintain a monitor application. Those that want to use it, should use old artifact.

**Comment by jarlah** [comment]
cron job?

**Comment by Cougar** [comment]
What about adding [Prometheus client](https://github.com/prometheus/client_java) to modules? Of course this needs to some more investigation what metrics are meaningful and should be collected. Any thoughts?

**Comment by jarlah** [comment]
it might be a good idea. But right now I have brought back the old monitor back from the dead, stripped for all unnecessary features. It only checks if modules are up. Closing this issue since.
