### ISSUE TITLE
[tr069] Should manual xml creation be replaced with something more readable

### ISSUE THREAD

**Issue by jarlah** [freeacs/freeacs#92]

**Comment by dror27** [comment]
Could you please provide a clue as to manually create the xml files? Thanx

**Comment by jarlah** [comment]
in code
```
String xml = "<Whatever>" + OK + "</Whatever>";
```
service should just send an instance of Whatever to a SOAP marshaller.

**Comment by jarlah** [comment]
but i am not sure if i am ever going to do this

**Comment by dror27** [comment]
Sorry - I though this issue related to the creation of the classes in com.github.freeacs.ws.xml ... I have since generated them manually using xjc (as I could not find the automation for it). Very nice project. Feel free to erase this whole thread.

**Comment by jarlah** [comment]
Install sbt and run sbt clean compile. Can go without clean also. And use intellij with Scala plugin (provides sbt) to open project

**Comment by jarlah** [comment]
Then you will get automatic xsd to webservice classes

**Comment by jarlah** [comment]
If you just need the classes you can of course skip intellij. But any contributions is Nice:)

**Comment by dror27** [comment]
Thank you for the quick response. Enjoy :)

**Comment by jarlah** [comment]
No problem. I usually respond fast only when i immediately know the context and what to reply. Closing.
